### PR TITLE
Add Languagefile DE_DE and some little fixes

### LINKED ISSUE #406: [BUG] Grafical Issue on /Flan info -> Name of Co Owner changed allways to Owner
### Modloader

Fabric

### Minecraft version

1.21.1

### Modloader version

fabric 

### Mod version

flan-1.21.1-1.12.0-fabric

### Description

Hey, i had found an little grafical issue.

If i add an Other  Co-Owner, it shows on /flan info the right name, but when they went off, it shows my Own name.

Image

And also in the UI, it shows my Head, but the name is Right, and in the Config the UUIS is also right.

Image

### Steps to reproduce

Add Online Player to Co Owner
Player Go Oflline
Name in Info shows as Own name, Head in the UI is also Own  Head, but name is right

### Mods that might affect the issue

_No response_

### Logs

No Logs for this issue

### LINKED ISSUE #408: [BUG or Suggestion] Issue on depth with Subclaim
### Modloader

Fabric

### Minecraft version

Fabric 1.21.1

### Modloader version

Fabric 0.16.14

### Mod version

flan-1.21.1-1.12.0-fabric

### Description

I'm Splitting now my Issue https://github.com/Flemmli97/Flan/issues/407

Here is the Issue what i get with Subclaims:

I had added the defaultClaimDepth on my config to 384, if i add an claim on the heigh from 320, to get to -64, but it use allways the point of the SubClaim position, The Claim does work right on -64 but the Subclaim does not work with this depth

All Permissions are parenting, only the Heigh / Depth is not sync to Subclaims or it does not used in Subclaims.

I think in the Config could be an option, "Should Subclaims have also the default Depth" -> true 
Then it use the defaultDepth, if not, use the position, where the claim is generating. 

```

  {
    "ID": "b55f89fe-7c56-4db2-866d-8b6e313ef663",
    "Name": "NudelTown",
    "PosxXzZY": [
      -165,
      683,
      -214,
      429,
      -64 //<- This is the right heigh, what used with the depth setting in the Config
    ],
    "Home": [
      271,
      117,
      170
    ],
    "EnterTitle": "{\"text\":\"This is Nudeltown\",\"italic\":false,\"color\":\"white\"}",
    "EnterSubtitle": "{\"text\":\"This is the City, you get a Claim from an Admin\",\"italic\":false,\"color\":\"white\"}",
    "LeaveTitle": "{\"text\":\" \",\"italic\":false,\"color\":\"white\"}",
    "LeaveSubtitle": "{\"text\":\"You left a secured area!\",\"italic\":false,\"color\":\"white\"}",
    "Potions": {},
    "AllowedEntries": {},
    "GlobalPerms": [
      "flan:enderman",
      "flan:drop",
      "flan:can_stay",
      "flan:open_container",
      "flan:snow_golem",
      "flan:enchantment",
      "flan:lock_items",
      "flan:portal",
      "flan:flight",
      "flan:pickup",
      "flan:enderchest"
    ],
    "PermGroup": {
      "Visitor": {
        "flan:door": true,
        "flan:button_lever": true,
        "flan:pressure_plate": true,
        "flan:enchantment": true,
        "flan:trapdoor": true,
        "flan:fence_gate": true,
        "flan:portal": true,
        "flan:enderchest": true,
        "flan:bed": true,
        "flan:itemframe_rotate": true,
        "flan:trading": true
      },
      "Co-Owner": {
        "flan:armorstand": true,
        "flan:archeology": true,
        "flan:edit_claim": true,
        "flan:projectiles": true,
        "flan:button_lever": true,
        "flan:break": true,
        "flan:pickup": true,
        "flan:enderchest": true,
        "flan:edit_perms": true,
        "flan:can_stay": true,
        "flan:open_container": true,
        "flan:boat": true,
        "flan:lectern_take": true,
        "flan:pressure_plate": true,
        "flan:noteblock": true,
        "flan:place": true,
        "flan:portal": true,
        "flan:hurt_animal": true,
        "flan:trample": true,
        "flan:wind_charge": true,
        "flan:ender_pearl": true,
        "flan:target_block": true,
        "flan:break_non_living": true,
        "flan:endcrystal_place": true,
        "flan:drop": true,
        "flan:claim_message": true,
        "flan:anvil": true,
        "flan:door": true,
        "flan:interact_sign": true,
        "flan:fence_gate": true,
        "flan:chorus_fruit": true,
        "flan:xp": true,
        "flan:hurt_named": true,
        "flan:jukebox": true,
        "flan:animal_interact": true,
        "flan:minecart": true,
        "flan:raid": true,
        "flan:enchantment": true,
        "flan:beacon": true,
        "flan:trapdoor": true,
        "flan:interact_block": true,
        "flan:redstone": true,
        "flan:bucket": true,
        "flan:bed": true,
        "flan:trading": true,
        "flan:itemframe_rotate": true
      }
    },
    "PlayerPerms": {
      "xxx": "Co-Owner",
      "xxx": "Co-Owner",
      "xxx": "Co-Owner"
    },
    "SubClaims": [
      {
        "ID": "aadfa560-733b-425d-ab25-51048d30576c",
        "Name": "MissesCharmy",
        "PosxXzZY": [
          272,
          369,
          -88,
          -26,
          -64 //<- Had changed this per hand, because it has used the position where i had claimed the SUBCLAIM this should be also as Parent, because i want to use the full heigh from the claim
        ],
        "Home": [
          320,
          91,
          -57
        ],
        "EnterTitle": "",
        "EnterSubtitle": "",
        "LeaveTitle": "",
        "LeaveSubtitle": "",
        "Potions": {},
        "Parent": "b55f89fe-7c56-4db2-866d-8b6e313ef663",
        "AllowedEntries": {},
        "GlobalPerms": {
          "flan:enderman": true,
          "flan:drop": true,
          "flan:can_stay": true,
          "flan:snow_golem": true,
          "flan:enchantment": true,
          "flan:lock_items": true,
          "flan:portal": true,
          "flan:flight": true,
          "flan:pickup": true,
          "flan:enderchest": true
        },
        "PermGroup": {
          "Visitor": {
            "flan:door": true,
            "flan:button_lever": true,
            "flan:pressure_plate": true,
            "flan:enchantment": true,
            "flan:trapdoor": true,
            "flan:fence_gate": true,
            "flan:portal": true,
            "flan:enderchest": true,
            "flan:bed": true,
            "flan:itemframe_rotate": true,
            "flan:trading": true
          },
          "Co-Owner": {
            "flan:armorstand": true,
            "flan:archeology": true,
            "flan:edit_claim": true,
            "flan:projectiles": true,
            "flan:button_lever": true,
            "flan:break": true,
            "flan:pickup": true,
            "flan:enderchest": true,
            "flan:edit_perms": true,
            "flan:can_stay": true,
            "flan:open_container": true,
            "flan:boat": true,
            "flan:lectern_take": true,
            "flan:pressure_plate": true,
            "flan:noteblock": true,
            "flan:place": true,
            "flan:portal": true,
            "flan:hurt_animal": true,
            "flan:trample": true,
            "flan:wind_charge": true,
            "flan:ender_pearl": true,
            "flan:target_block": true,
            "flan:break_non_living": true,
            "flan:endcrystal_place": true,
            "flan:drop": true,
            "flan:claim_message": true,
            "flan:anvil": true,
            "flan:door": true,
            "flan:interact_sign": true,
            "flan:fence_gate": true,
            "flan:chorus_fruit": true,
            "flan:xp": true,
            "flan:hurt_named": true,
            "flan:jukebox": true,
            "flan:animal_interact": true,
            "flan:minecart": true,
            "flan:raid": true,
            "flan:enchantment": true,
            "flan:beacon": true,
            "flan:trapdoor": true,
            "flan:interact_block": true,
            "flan:redstone": true,
            "flan:bucket": true,
            "flan:bed": true,
            "flan:trading": true,
            "flan:itemframe_rotate": true
          }
        },
        "PlayerPerms": {
          "xxx": "Co-Owner"
        }
      },
      {
        "ID": "0fb3bb4e-6b1b-4c31-a138-09a1e3f6d00a",
        "Name": "EvilFabee",
        "PosxXzZY": [
          260,
          279,
          164,
          187,
          -64 //<- Had changed this per hand, because it has used the position where i had claimed the SUBCLAIM this should be also as Parent, because i want to use the full heigh from the claim
        ],
        "Home": [
          269,
          117,
          175
        ],
        "EnterTitle": "",
        "EnterSubtitle": "",
        "LeaveTitle": "",
        "LeaveSubtitle": "",
        "Potions": {},
        "Parent": "b55f89fe-7c56-4db2-866d-8b6e313ef663",
        "AllowedEntries": {},
        "GlobalPerms": {
          "flan:enderman": true,
          "flan:drop": true,
          "flan:can_stay": true,
          "flan:snow_golem": true,
          "flan:enchantment": true,
          "flan:lock_items": true,
          "flan:portal": true,
          "flan:flight": true,
          "flan:pickup": true,
          "flan:enderchest": true
        },
        "PermGroup": {
          "Visitor": {
            "flan:door": true,
            "flan:button_lever": true,
            "flan:pressure_plate": true,
            "flan:enchantment": true,
            "flan:trapdoor": true,
            "flan:fence_gate": true,
            "flan:portal": true,
            "flan:enderchest": true,
            "flan:bed": true,
            "flan:itemframe_rotate": true,
            "flan:trading": true
          },
          "Co-Owner": {
            "flan:armorstand": true,
            "flan:archeology": true,
            "flan:edit_claim": true,
            "flan:projectiles": true,
            "flan:button_lever": true,
            "flan:break": true,
            "flan:pickup": true,
            "flan:enderchest": true,
            "flan:edit_perms": true,
            "flan:can_stay": true,
            "flan:open_container": true,
            "flan:boat": true,
            "flan:lectern_take": true,
            "flan:pressure_plate": true,
            "flan:noteblock": true,
            "flan:place": true,
            "flan:portal": true,
            "flan:hurt_animal": true,
            "flan:trample": true,
            "flan:wind_charge": true,
            "flan:ender_pearl": true,
            "flan:target_block": true,
            "flan:break_non_living": true,
            "flan:endcrystal_place": true,
            "flan:drop": true,
            "flan:claim_message": true,
            "flan:anvil": true,
            "flan:door": true,
            "flan:interact_sign": true,
            "flan:fence_gate": true,
            "flan:chorus_fruit": true,
            "flan:xp": true,
            "flan:hurt_named": true,
            "flan:jukebox": true,
            "flan:animal_interact": true,
            "flan:minecart": true,
            "flan:raid": true,
            "flan:enchantment": true,
            "flan:beacon": true,
            "flan:trapdoor": true,
            "flan:interact_block": true,
            "flan:redstone": true,
            "flan:bucket": true,
            "flan:bed": true,
            "flan:trading": true,
            "flan:itemframe_rotate": true
          }
        },
        "PlayerPerms": {
          "xxx": "Co-Owner"
        }
      }
    ]
  }

```

### Steps to reproduce

1. Add Flan,
2. Create Claim
3. Create Subclaim

### Mods that might affect the issue

_No response_

### Logs

No log here

### PR DESCRIPTION
**Pull request by suerion**
This should add the german language file

Then it fixes:
https://github.com/Flemmli97/Flan/issues/406

And it update the issue with subclaims and there depth/heigh etc from 
https://github.com/Flemmli97/Flan/issues/408

The Language file is yet not finished, thats why this pull should be a draft

### CODE REVIEW

**Comment by suerion** [comment]
Had added subclaim expanding with checks for parent claims etc.

**Comment by suerion** [comment]
@Flemmli97 you could look if this would work, should fix the little issues and added German language, 

and i had added subclaim expanding <- Subclaim expanding needs to be tested

**Comment by suerion** [comment]
Claim expanding works but not right now, will need a little bit testing!

**Comment by suerion** [comment]
Okey, tests are finished,

Fixed #406 
Fixed #408 

-Added German Language File
-Added Subclaim Expanding -> Refactoring a little bit of code

**Comment by suerion** [comment]
@Flemmli97 for testing -> Artifact
[flan-1.21.1-1.12.0-fabric.zip](https://github.com/user-attachments/files/21824708/flan-1.21.1-1.12.0-fabric.zip)

**Comment by suerion** [comment]
fixed the little issue, that the default claim get also maxY from 3D Claim

new Artifact build -> [flan-1.21.1-1.12.0-fabric.zip](https://github.com/user-attachments/files/21836108/flan-1.21.1-1.12.0-fabric.zip)

**Comment by suerion** [comment]
Argh, new Fix, had overwrited my logic
[flan-1.21.1-1.12.0-fabric.zip](https://github.com/user-attachments/files/21936526/flan-1.21.1-1.12.0-fabric.zip)

now here is the final version
and fixed again  https://github.com/Flemmli97/Flan/issues/408

**Review by Flemmli97 — CHANGES_REQUESTED** [review]
dont edit the files in generated as the files there are automatically generated. they will get overwritten with the next datagen.

add the default lang to the datagen stuff

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java [hunk 1]
```diff
@@ -22,6 +22,13 @@ public boolean intersects(double x, double y, double z, double X, double Y, doub
         return this.minX < X && this.maxX > x && this.minY < Y && this.maxY > y && this.minZ < Z && this.maxZ > z;
     }
 
+    //help to get claims in other claims
+    public boolean contains(BlockPos pos) {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java]: there already is a method doing exactly this above. this is duplicate code

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java [hunk 2]
```diff
@@ -410,31 +410,65 @@ private UUID generateUUID() {
...
+            sub.maxY = Math.max(pos1.getY(), pos2.getY());
+        } else {
+            if (ConfigHandler.CONFIG.subClaimsInheritParentDepth) {
+                //if parent inherit depth true, use parent minY
+                Claim firstParent = this;
+                while (firstParent.parentClaim() != null) {
+                    firstParent = firstParent.parentClaim();
+                }
+                sub.minY = firstParent.minY;
+                // maxY should be null
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: dont think this comment is needed?

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java [hunk 3]
```diff
@@ -410,31 +410,65 @@ private UUID generateUUID() {
...
+            }
+            //for 2d use y from player
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: dangling comment?

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java [hunk 4]
```diff
@@ -410,31 +410,65 @@ private UUID generateUUID() {
...
+        }
+
+        // subclaim is not bigger as parent
+        ClaimBox parentBox = this.getDimensions();
+        ClaimBox subBox = sub.getDimensions();
+
+        if (subBox.minY() < parentBox.minY() || subBox.maxY() > parentBox.maxY()) {
+            // Subclaim geht über Parent-Grenzen hinaus - als Konflikt behandeln
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: german comment lol

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java [hunk 5]
```diff
@@ -30,9 +31,10 @@ public static boolean check(ServerPlayer player, BlockPos pos, Claim claim, Reso
         return hasPerm;
     }
 
+    //check if Claim or Subclaim at positions
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java]: no... dont do this. this is ONLY for main claims. this will break various other places

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java [hunk 6]
```diff
@@ -49,6 +51,32 @@ else if (!b.get())
...
+        player.displayClientMessage(
+                Component.translatable("flan.expandError")
+                        .append(translatedText(key, args))
+                        .withStyle(ChatFormatting.RED),
+                false
+        );
+    }
+
+    // only subclaim permission check
+    public static boolean checkSubclaimPerm(ServerPlayer player, Claim subclaim) {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java]: is it really neccessary to make a helper method that is used once?

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java [hunk 7]
```diff
@@ -49,6 +51,32 @@ else if (!b.get())
...
+        Claim parent = subclaim.parentClaim();
+        return parent != null && parent.canInteract(player, BuiltinPermission.EDITCLAIM, player.blockPosition());
+    }
+
+    //check if claim or subclaim
+    public static Claim getClaimOrSubclaimAt(ClaimStorage storage, BlockPos pos) {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java]: see comment at `checkReturn` dont think this is needed

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java [hunk 8]
```diff
@@ -49,6 +51,32 @@ else if (!b.get())
         });
     }
 
+    // if expand error is given
+    public static void sendExpandError(ServerPlayer player, String key, Object... args) {
+        player.displayClientMessage(
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java]: dont append it. pass it as an arg to the existing message. you would then also need to update the lang files

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java [hunk 9]
```diff
@@ -465,19 +479,41 @@ public List<Claim> getAllSubclaims() {
...
+        );
+
         Claim newClaim = new Claim(opposite, to, claim.claimID, this.level);
+
         if (claim.is3d()) {
-            newClaim.withHeight(Math.max(minY, to.getY()));
+            //resize in 3d
+            newClaim.minY = Math.min(opposite.getY(), to.getY());
+            newClaim.maxY = Math.max(opposite.getY(), to.getY());
+        } else {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: ~~im not seeing the point of the amount of changes here. its just written differently but achieves the same.~~

~~except for this else section~~

File: common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java [hunk 10]
```diff
@@ -890,26 +891,175 @@ public static int setClaimHome(CommandContext<CommandSourceStack> context) throw
...
-
         ClaimStorage storage = ClaimStorage.get(player.serverLevel());
+        ClaimMode mode = PlayerClaimData.get(player).getClaimMode();
+
         int amount = IntegerArgumentType.getInteger(context, "distance");
+
+        Claim claim;
+        if(mode.isSubclaim){
+            //Subclaim mode only use Subclaim
+            Claim mainClaim = storage.getClaimAt(player.blockPosition());
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: you can move the common part here out the if else

File: common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java [hunk 11]
```diff
@@ -890,26 +891,175 @@ public static int setClaimHome(CommandContext<CommandSourceStack> context) throw
...
+        // if distance is 0 it should not work and stop
+        if (amount <= 0) {
+            ClaimUtils.sendExpandError(player, "flan.invalidDistance");
+            return 0;
+        }
+
+        Direction facing = player.getDirection(); //saved the facing direction
+
+        //Adding Subclaims on expand
+        if (claim.isSubclaim()) {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: similar above. can just prob extract the expansion part out and just have it pass in a claim (whether sub or main) as an arg. since main claim should also have height expansion option if its 3d

**Comment by Flemmli97** [comment]
also other lang files dont need update as missing translations automatically default to english

**Comment by suerion** [comment]
> also other lang files dont need update as missing translations automatically default to english

@Flemmli97 hey, thanks for the informations, will edit back all languages files and will look on datagen, will come back with the commit ;)

**Comment by Flemmli97** [comment]
thinking about it the claim creation does not need any height adjusting so `tryCreateSubClaim` and `resizeSubclaim` does not require changes.
it is sufficient to return the proper bounds for subclaim so you could just change `Claim#getDimensions` for non 3d subclaims. this will also make sure that the height is always adjusted to the parent claim even if the parent bounds changes

**Comment by Flemmli97** [comment]
> > also other lang files dont need update as missing translations automatically default to english
> 
> @Flemmli97 hey, thanks for the informations, will edit back all languages files and will look on datagen, will come back with the commit ;)

see `ENLangGen`

**Comment by suerion** [comment]
> thinking about it the claim creation does not need any height adjusting so `tryCreateSubClaim` and `resizeSubclaim` does not require changes. it is sufficient to return the proper bounds for subclaim so you could just change `Claim#getDimensions` for non 3d subclaims. this will also make sure that the height is always adjusted to the parent claim even if the parent bounds changes

@Flemmli97 had changed the generating files,

will look on this changings, yes thats right, need only to change getDimensions(), but will look on it, and then come back

the requested, changings are fixed now.

**Comment by suerion** [comment]
Had changed all informations, hope thats right now ;)

**Comment by Flemmli97** [comment]
there are still pending change requests

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java [hunk 12]
```diff
@@ -410,30 +429,48 @@ private UUID generateUUID() {
     }
 
     public Set<Claim> tryCreateSubClaim(BlockPos pos1, BlockPos pos2, boolean is3d) {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: dont need the changes here with the dimension fix

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java [hunk 13]
```diff
@@ -465,19 +502,43 @@ public List<Claim> getAllSubclaims() {
 
     public Set<Claim> resizeSubclaim(Claim claim, BlockPos from, BlockPos to) {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: dont need the changes here with the dimension fix

File: neoforge/src/main/java/io/github/flemmli97/flan/data/ENLangGen.java [hunk 14]
```diff
@@ -223,7 +224,7 @@ protected void addTranslations() {
         this.add("flan.addIgnoreEntry", "Added %1$s to the claims ignore list %2$s");
         this.add("flan.removeIgnoreEntry", "Removed %1$s from the claims ignore list %2$s");
 
-        this.add("flan.confirmCommand", "Use '/flan confirm <confirm | deny>' to confirm or deny running this command.");
+        this.add("flan.confirmCommand", "Use '/flan confirm + <confirm | deny>' to confirm or deny running this command.");
```
Comment (Flemmli97) [inline neoforge/src/main/java/io/github/flemmli97/flan/data/ENLangGen.java:227]: why the +?
some people might think you need to type an actual + with this

**Review by Flemmli97 — CHANGES_REQUESTED** [review]

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java (hunk 4 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: oh no xD sorry, i had thougt, i had translated all comments

File: neoforge/src/main/java/io/github/flemmli97/flan/data/ENLangGen.java (hunk 14 above)
Comment (suerion) [reply neoforge/src/main/java/io/github/flemmli97/flan/data/ENLangGen.java:227]: because another people had said, they don'T understand, why the command is uses /flan confirm confirm on confirming,

thats only a thinking, this would help more, to add an confirm behind the "/flan confirm" because, our admins had thougt, "/flan confirm or /flan deny" is right, because of <confirm | deny> in the declaration

**Comment by suerion** [comment]
Will look on the another changings tomorow...

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java (hunk 3 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: deleted on changings of the old logic

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java (hunk 2 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: deleted on changings back to the old logic

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java (hunk 12 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: changings are redoing

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java (hunk 13 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: changings are redoing

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java (hunk 5 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java]: changed back to old version, that checkReturn is only used for main claims, getClaimOrSubclaimAt is not in use, but could be helpful in future, let it be there

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java (hunk 1 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java]: deleted contains block, because equals is the same, only fixed an issue on comparing between boxes

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java (hunk 4 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: because of redoing the context to old  this comment is not given anymore

File: common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java (hunk 10 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: had refactored complette expand command.... need to perform test before...

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java (hunk 1 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java]: overthinked this, we need for inherit not the exactly checking the same box, thats why we need for subclaims the contain check, if another box need to be inside of the box, that we check here...

Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java]: need to check again, i'm too tired today, was an mistake on my side!

File: neoforge/src/main/java/io/github/flemmli97/flan/data/ENLangGen.java (hunk 14 above)
Comment (suerion) [reply neoforge/src/main/java/io/github/flemmli97/flan/data/ENLangGen.java:227]: I would let it added yet, if i need to change it back, say it to me.

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java (hunk 1 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/ClaimBox.java]: Had fixed this, yes we need to check, if we are insed of the box, not the same box corners,

File: common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java (hunk 11 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: had updated it

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java (hunk 6 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java]: had deleted the helper method and added check in commandClaim

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java (hunk 7 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java]: deleted method

File: common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java (hunk 8 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/ClaimUtils.java]: had changed it to the args

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java [hunk 15]
```diff
@@ -592,7 +611,7 @@ public List<String> groups() {
     }
 
     public boolean setHomePos(BlockPos homePos) {
-        if (this.insideClaim(homePos)) {
+        if (this.getDimensions().insideClaim(homePos)) {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: why this?

File: common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java [hunk 16]
```diff
@@ -888,28 +889,154 @@ public static int setClaimHome(CommandContext<CommandSourceStack> context) throw
...
-            return 0;
-
         ClaimStorage storage = ClaimStorage.get(player.serverLevel());
+        ClaimMode mode = PlayerClaimData.get(player).getClaimMode();
         int amount = IntegerArgumentType.getInteger(context, "distance");
-        ClaimBox dims = claim.getDimensions();
+
+        //is claim parent or subclaim
+        Claim claim = findClaim(player, storage, mode);
+        if (claim == null) return 0;
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: should prob send a message if there is no claim

Comment (Flemmli97) [reply common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: just take the messages from other command where claim is not found

File: common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java [hunk 17]
```diff
@@ -888,28 +889,154 @@ public static int setClaimHome(CommandContext<CommandSourceStack> context) throw
...
+        );
+
+        // math from blocks!
+        int newWidth = newBox.maxX() - newBox.minX() + 1;
+        int newLength = newBox.maxZ() - newBox.minZ() + 1;
+        int newHeight = newBox.maxY() - newBox.minY() + 1;
+
+        int totalBlocks = mode.is3d ? newWidth * newLength * newHeight : newWidth * newLength;
+
+        if (totalBlocks > ConfigHandler.CONFIG.maxClaimBlocks) {
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: no this check is wrong. the config is the max claim blocks a player can gain over time.
you need to check if the player has enough claim blocks. see `PlayerData#canUseClaimBlocks`.
do also not that currently that always assumes 2d. so height should be ignored. Claim height does not use up claim blocks

Comment (Flemmli97) [reply common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: also subclaims should not use up claimblocks obviously so the check should be done only for main

File: common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java [hunk 18]
```diff
@@ -888,28 +889,154 @@ public static int setClaimHome(CommandContext<CommandSourceStack> context) throw
...
+            ClaimUtils.sendExpandError(player, "flan.expandTooLarge");
+            return 0;
+        }
+
+        //check if inherit of parent
+        if (claim.isSubclaim()) {
+            Claim parent = claim.parentClaim();
+            if (parent != null && !parent.getDimensions().contains(newBox)) {
+                ClaimUtils.sendExpandError(player, "flan.expandBeyondParent");
```
Comment (Flemmli97) [inline common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: tbh maybe it might be better to just expand to the parents bound if its too big but thats just me.
player wont need to calculate their current position till the border then and can just use a big number

**Review by Flemmli97 — CHANGES_REQUESTED** [review]

File: common/src/main/java/io/github/flemmli97/flan/claim/Claim.java (hunk 15 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/claim/Claim.java]: Becaus this gives a ClaimBox back, that would gives an Y, in 2D would this not checked, it would be only in 3D, thats the issue here, it trys the check, if the home is in the Claim

File: common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java (hunk 16 above)
Comment (suerion) [reply common/src/main/java/io/github/flemmli97/flan/commands/CommandClaim.java]: Had added now again the noClaim Message

**Comment by Flemmli97** [comment]
fixed the command. and a lot of things weren't needed there too
